<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Ayushi" failures="2" tests="2" name="MicrosoftEdge" time="94.994" errors="0" timestamp="2025-04-20T17:53:55 PDT">
  <testcase classname="TestCases.TC001_AccountregistrationTest" name="verify_account_registration" time="40.241">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestCases.TC001_AccountregistrationTest.verify_account_registration(TC001_AccountregistrationTest.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
at java.base/java.lang.Thread.run(Thread.java:1447)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verify_account_registration -->
  <testcase classname="TestCases.TC002_LoginTest" name="verify_login" time="40.283">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestCases.TC002_LoginTest.verify_login(TC002_LoginTest.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
at java.base/java.lang.Thread.run(Thread.java:1447)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verify_login -->
</testsuite> <!-- MicrosoftEdge -->
